"""initial schema

Revision ID: 6fc758da09b3
Revises:
Create Date: 2026-09-22 14:43:14.182272
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fc758da09b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("location_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("location_id"),
        sa.UniqueConstraint("location_key"),
        schema="core",
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("dag_id", sa.String(length=200), nullable=False),
        sa.Column("task_id", sa.String(length=200), nullable=False),
        sa.Column("dag_run_id", sa.String(length=200), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rows_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed')", name="ck_pipeline_run_status"
        ),
        sa.PrimaryKeyConstraint("run_id"),
        schema="ops",
    )
    op.create_index(
        "ix_pipeline_runs_dag_started",
        "pipeline_runs",
        ["dag_id", "started_at"],
        unique=False,
        schema="ops",
    )
    op.create_index(
        "ix_pipeline_runs_status", "pipeline_runs", ["status"], unique=False, schema="ops"
    )
    op.create_table(
        "weather_features",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("feature_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_set_version", sa.SmallInteger(), nullable=False),
        sa.Column("lag_temp_1h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("lag_temp_3h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("lag_temp_6h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("rolling_mean_temp_3h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("rolling_std_temp_3h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("rolling_mean_temp_6h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("temp_rate_of_change_1h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("pressure_delta_1h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("pressure_trend_3h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("lag_humidity_1h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("rolling_mean_humidity_3h", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("hour_sin", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("hour_cos", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("doy_sin", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("doy_cos", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("heat_index_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dew_point_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_chill_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("aqi_composite_risk_score", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("aqi_risk_level", sa.String(length=20), nullable=True),
        sa.Column("storm_indicator", sa.Boolean(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["core.locations.location_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "feature_time", name="uq_features_location_time"),
        schema="features",
    )
    op.create_index(
        "ix_features_location_time",
        "weather_features",
        ["location_id", "feature_time"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "data_quality_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("check_name", sa.String(length=100), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name="ck_dq_severity"),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["core.locations.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ops.pipeline_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ops",
    )
    op.create_index(
        "ix_dq_checked_at", "data_quality_checks", ["checked_at"], unique=False, schema="ops"
    )
    op.create_index(
        "ix_dq_failed_critical",
        "data_quality_checks",
        ["severity", "passed"],
        unique=False,
        schema="ops",
        postgresql_where=sa.text("NOT passed"),
    )
    op.create_table(
        "model_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "predicted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("horizon_hours", sa.SmallInteger(), nullable=False),
        sa.Column("predicted_temp_c", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=20), nullable=False),
        sa.Column("model_alias", sa.String(length=20), nullable=False),
        sa.Column("input_feature_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_temp_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["core.locations.location_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ops",
    )
    op.create_index(
        "ix_predictions_location_time",
        "model_predictions",
        ["location_id", "predicted_at"],
        unique=False,
        schema="ops",
    )
    op.create_table(
        "weather_observations_raw",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.Integer(), nullable=True),
        sa.Column("error_info", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ops.pipeline_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["core.locations.location_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.create_index(
        "ix_raw_obs_is_error",
        "weather_observations_raw",
        ["is_error"],
        unique=False,
        schema="raw",
        postgresql_where=sa.text("is_error"),
    )
    op.create_index(
        "ix_raw_obs_location_fetched",
        "weather_observations_raw",
        ["location_id", "fetched_at"],
        unique=False,
        schema="raw",
    )
    op.create_table(
        "weather_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("observation_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("feelslike_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("humidity_pct", sa.SmallInteger(), nullable=True),
        sa.Column("pressure_hpa", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("wind_speed_kph", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wind_degree", sa.SmallInteger(), nullable=True),
        sa.Column("wind_dir", sa.String(length=10), nullable=True),
        sa.Column("precip_mm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cloudcover_pct", sa.SmallInteger(), nullable=True),
        sa.Column("uv_index", sa.SmallInteger(), nullable=True),
        sa.Column("visibility_km", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weather_code", sa.SmallInteger(), nullable=True),
        sa.Column("weather_description", sa.String(length=200), nullable=True),
        sa.Column("is_day", sa.Boolean(), nullable=True),
        sa.Column("sunrise", sa.Time(), nullable=True),
        sa.Column("sunset", sa.Time(), nullable=True),
        sa.Column("moon_phase", sa.String(length=50), nullable=True),
        sa.Column("moon_illumination_pct", sa.SmallInteger(), nullable=True),
        sa.Column("aqi_co", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_no2", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_o3", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_so2", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_pm2_5", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_pm10", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("aqi_us_epa_index", sa.SmallInteger(), nullable=True),
        sa.Column("aqi_gb_defra_index", sa.SmallInteger(), nullable=True),
        sa.Column("raw_observation_id", sa.Integer(), nullable=True),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ops.pipeline_runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["core.locations.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_observation_id"],
            ["raw.weather_observations_raw.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "observation_time", name="uq_core_obs_location_time"),
        schema="core",
    )
    op.create_index(
        "ix_core_obs_location_time",
        "weather_observations",
        ["location_id", "observation_time"],
        unique=False,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_core_obs_location_time", table_name="weather_observations", schema="core")
    op.drop_table("weather_observations", schema="core")
    op.drop_index(
        "ix_raw_obs_location_fetched", table_name="weather_observations_raw", schema="raw"
    )
    op.drop_index(
        "ix_raw_obs_is_error",
        table_name="weather_observations_raw",
        schema="raw",
        postgresql_where=sa.text("is_error"),
    )
    op.drop_table("weather_observations_raw", schema="raw")
    op.drop_index("ix_predictions_location_time", table_name="model_predictions", schema="ops")
    op.drop_table("model_predictions", schema="ops")
    op.drop_index(
        "ix_dq_failed_critical",
        table_name="data_quality_checks",
        schema="ops",
        postgresql_where=sa.text("NOT passed"),
    )
    op.drop_index("ix_dq_checked_at", table_name="data_quality_checks", schema="ops")
    op.drop_table("data_quality_checks", schema="ops")
    op.drop_index("ix_features_location_time", table_name="weather_features", schema="features")
    op.drop_table("weather_features", schema="features")
    op.drop_index("ix_pipeline_runs_status", table_name="pipeline_runs", schema="ops")
    op.drop_index("ix_pipeline_runs_dag_started", table_name="pipeline_runs", schema="ops")
    op.drop_table("pipeline_runs", schema="ops")
    op.drop_table("locations", schema="core")
    # ### end Alembic commands ###
